mysql:
  username: 'root'
  host: localhost
  enable: true
  password: ''
  database: bukkit
  port: 3306
defaults:
  speed: 10
  stamina: 10
  bodyfat: 10
  muscle: 10
edibles:
- material: APPLE
  fat: 2
  protein: 3
- material: BREAD
  fat: 5
  protein: 1