name: PlayerAttributes
main: playerattributes.PlayerAttributes
version: 1.0
description: Player Attributes
author: Gu3rr1lla
database: false
commands:
  pastats:
    description: Displays stats.
    usage: /pastats